package es.cristcd.taskcompanion.parser
object Patterns {
    val BLOCK_QUOTATION_PATTERN = Regex("^bq(?<attributes>.*?)(?<mode>\\.{1,2})(?::(?<cite>.+?))? ")
    val CODE_BLOCK_PATTERN = Regex("^bc(?<attributes>.*?)(?<mode>\\.{1,2}) ")
    val COMMENT_PATTERN = Regex("^#{3}(?<mode>\\.{1,2}) ")
    val HEADING_PATTERN = Regex("^h(?<level>[1-6])(?<attributes>.*)\\. ")
    val NO_TEXTILE_BLOCK_PATTERN = Regex("^notextile(?<mode>\\.{1,2}) ")
    val PARAGRAPH_PATTERN = Regex("(?:^p(?<attributes>.*)\\. )?")
    val PRE_PATTERN = Regex("^pre(?<attributes>.*?)(?<mode>\\.{1,2}) ")
    val ORDERED_LIST_PATTERN = Regex("(?<level>#+)(?<attributes>(?:[\\[\\{\\(].+?[\\]\\}\\)])*)(?<start>\\d+)?(?:(?:\\. *)|(?: +)|(?:_ +))")
    val UNORDERED_LIST_PATTERN = Regex("(?<level>\\*+)(?<attributes>(?:[\\[\\{\\(].+?[\\]\\}\\)])*)(?:(?:\\. *)|(?: +)|(?:_ +))")

    val ABBREVIATION_PATTERN = Regex("""^(?<abbreviation>\p{Lu}{3,})\((?<description>.+?)\)""")
    val BOLD_TEXT_PATTERN = Regex("""^(?<count1>\*+)(?<string>.+?)(?<count2>\*+)""")
    val CITATION_PATTERN = Regex("""^\?\?(?<string>.+?)\?\?""")
    val CODE_PATTERN = Regex("^@(?<code>.*?)@")
    val IMAGE_PATTERN = Regex("^!(?<align>[<|>|=]?)(?<string>.+?)!(?::(?<href>[^ \\(\\)]+))?")
    val IMAGE_ALT_PATTERN = Regex("(?:\\(([^\\(\\)]+)\\))?$")
    val ITALIC_TEXT_PATTERN = Regex("^(?<count1>_+)(?<string>.+?)(?<count2>_+)")
    val LINK_PATTERN = Regex("^\"(?<string>.+?)\":(?<href>[^ \\(\\)]+)")
    val LINK_TITLE_PATTERN = Regex("(?:\\(([^\\(\\)]+)\\))?$")
    val NO_TEXTILE_INLINE_PATTERN = Regex("^={2}(?<string>.*?)={2}")
    val SPAN_PATTERN = Regex("^(?<count1>%+)(?<string>.+?)(?<count2>%+)")
    val DELETION_TEXT_PATTERN = Regex("^ (?<count1>-+)(?<string>.+?)(?<count2>-+)")
    val SUBSCRIPT_TEXT_PATTERN = Regex("^(?<count1>~+)(?<string>.+?)(?<count2>~+)")
    val SUPERSCRIPT_TEXT_PATTERN = Regex("""^(?<count1>\^+)(?<string>.+?)(?<count2>\^+)""")
    val INSERTION_TEXT_PATTERN = Regex("""^(?<count1>\++)(?<string>.+?)(?<count2>\++)""")

    val ATTRS_STR_PATTERN = Regex("(?:^([\\[\\{\\(].+?[\\]\\}\\)])*)")
    val PADDING_PATTERN = Regex("\\(+|\\)+")
    val ALIGN_PATTERN = Regex("[<|>|=]{1,2}")
    val LANG_PATTERN = Regex("\\[([A-Za-z]{2}(?:-[A-Za-z]{2})?)\\]")
    val CLASS_ID_PATTERN = Regex("\\((?<class>[\\w-_\\. ]+)?(?:#(?<id>[\\w-_]+))?\\)")
    val CSS_PROPS_PATTERN = Regex("\\{([^\\{\\}]+)\\}")
    val CSS_PROPS_SPLIT_PATTERN = Regex("; *")
    val CSS_PROP_STR_PATTERN = Regex("(?<key>[a-z-_]+): *(?<value>.+)")
}